{
    'name': 'Job_card',
    'version': '17.0',
    'summary': 'Manage Service',
    'sequence': 1,
    'description': 'Module to manage AC details, warranty start and end dates',
    'category': 'Vendor',
    'author': 'Sismatix',
    'website': 'http://sismatix.co',
    'depends': ['contacts', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/partner_asset_views.xml',
        'views/asset_brand_views.xml',
        'views/user_views.xml',
        'views/partner_views.xml',
        'views/product_commission_views.xml',
        'views/asset_service_views.xml',
        'views/job_reason_views.xml',
        'data/job_service_data.xml',
        'wizards/job_reason_wizard.xml',
    ],
    
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
